GET http://localhost:8082/ HTTP/1.1

POST http://localhost:8082/update HTTP/1.1
Host: localhost:8082
Content-Type: application/json

{
  "id": "Alloc",
  "type": "gauge",
  "value": 1744184459
}

POST http://localhost:8082/value HTTP/1.1
Host: localhost:8082
Content-Type: application/json

{
  "id": "PollCount",
  "type": "counter"
} 